[package]
name = "hermes"
version = "0.1.0"
authors = ["Bheesham Persaud <bheesham.persaud@live.ca>"]

[dependencies]
bitflags = "0.4.0"
lettre = "0.5"
mio = "0.5.0"
nom = "1.2.1"

[dependencies.openssl]
version = "0.7.6"
features = ["ecdh_auto", "tlsv1_1", "tlsv1_2"]
